apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-watcher
  namespace: secret-watch-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-watcher
  namespace: secret-watch-demo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-watcher
  namespace: secret-watch-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-watcher
subjects:
- kind: ServiceAccount
  name: secret-watcher
  namespace: secret-watch-demo
