apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-watcher-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tyrellshawn/minikube-secret-watch.git
    path: k8s
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: secret-watch-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
